### ISSUE TITLE
Added an "echo input" feature

### ISSUE THREAD

**Issue by bdealey** [senzing-garage/g2command#144]
There are times when I generate a large set of reevaluateEntity messages to process via G2Command.py and I pass them in via a file with the command:
G2Explorer.py < myFile.txt

I set TIMER to get an indication that commands are running, but I would also like the ability to enable a ECHO mode which prints the input command back to me.  The main reason for this is so I can guage how much of my file has been processed and how much remains to be processed.

**Comment by jamietypovsky** [comment]
Not selected for development.
